name: rust-internet-tunnel
version: "0.0.1"
author: Tomas Jakstas <tom.jakstas@gmail.com>
about: control traffic for your interface
args:
    - config:
        short: c
        long: config
        value_name: FILE
        help: "ruleset file to load"
        takes_value: true
    - interface-name:
        short: i
        long: interface-name
        help: "tun interface name default tun0"
        takes_value: true
    - interface-ip:
        short: p
        long: interface-ip
        help: "tun interface ip default 10.0.0.1"
        takes_value: true
    - forward:
        short: f
        long: forward-ip
        help: "ip used to forward traffic further default 10.0.0.2"
        takes_value: true
    - verbose:
        short: v
        long: verbose
        multiple: true
        help: sets the level of logging verbosity default info